// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBtCzx_g3TIxeKnfv2bPbW8GRVredqUF9Q',
    appId: '1:1018057238860:web:308eaf88824ee49845c7e9',
    messagingSenderId: '1018057238860',
    projectId: 'fliplaptop-80b95',
    authDomain: 'fliplaptop-80b95.firebaseapp.com',
    storageBucket: 'fliplaptop-80b95.appspot.com',
    measurementId: 'G-M3T1GTPCJV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjQrX_d1xaL-J-W2QDRlehT1Hdp_0zTDc',
    appId: '1:1018057238860:android:f2a6b6b721a617f245c7e9',
    messagingSenderId: '1018057238860',
    projectId: 'fliplaptop-80b95',
    storageBucket: 'fliplaptop-80b95.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwin1li3vzBcN7lFD_qF0YjYSuzCyLaV0',
    appId: '1:1018057238860:ios:8ee33e4a7a2865cb45c7e9',
    messagingSenderId: '1018057238860',
    projectId: 'fliplaptop-80b95',
    storageBucket: 'fliplaptop-80b95.appspot.com',
    iosClientId: '1018057238860-h2vv3r3iluhmukei3r6qfnuqkbu9t33v.apps.googleusercontent.com',
    iosBundleId: 'com.thesuitch.fliplaptop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwin1li3vzBcN7lFD_qF0YjYSuzCyLaV0',
    appId: '1:1018057238860:ios:8ee33e4a7a2865cb45c7e9',
    messagingSenderId: '1018057238860',
    projectId: 'fliplaptop-80b95',
    storageBucket: 'fliplaptop-80b95.appspot.com',
    iosClientId: '1018057238860-h2vv3r3iluhmukei3r6qfnuqkbu9t33v.apps.googleusercontent.com',
    iosBundleId: 'com.thesuitch.fliplaptop',
  );
}
